version: '2'

services:
    flask:
        build:
            context: .
            dockerfile: docker/dockerfiles/flask.dockerfile
        #volumes:
          #- ./lupify:/app
          #- .:/app
        networks:
          - flask-network
    lupify-scanner:
        build:
            context: .
            dockerfile: docker/dockerfiles/lupify-scanner.dockerfile
        depends_on:
          - "mongo"
        networks:
          - mongo-network
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
          - flask-network
          - mongo-network

networks:
    flask-network:
        driver: bridge
    mongo-network:
        driver: bridge
